### ISSUE TITLE
Protected Routes / Authorization Headers SSR Problem

### ISSUE THREAD

**Issue by emdede** [OrJDev/solid-auth#1]
Hi! First off, I'm glad to see that you went ahead and released a follow-up version, seeing that your changes to next-auth are a bit stalled. I appreciate your work on this!

I ran into an issue that has been blocking me for several hours already and I can't seem to overcome it. It is actually more of a general Solid problem but because of the tight coupling of the problem with Auth I was hoping it'd be okay if I raise this here.

I have following setup (simplified):
```tsx
<SessionProvider>
  <APIProvider>
    <Routes />
  </API>
</Session>
```

Routes are
```
login.tsx
(app).tsx <--- auth-protected entry point layout
app/
  all my routes...
```

I have implemented Credentialsprovider (which took much longer than I had liked) and it is working fine!

However due to some implementation detail I am facing a big obstacle.
The `APIProvider` listens to session changes and sets an `accessToken` (that is included in the session data) as an `Authorization` header.
CSR (login first and get redirected into protected space) is working because the session - including the token - is available after signin.
However, if there is an SSR request to a nested route that uses the API. I can no longer use my setup because the session has not yet been initialized and the Authorization header is not set.

Now, I could probably micromanage this and go into every single sub-route to tell the API request to wait for the session to be retrieved first but it's tedious and brittle. I'm thinking there must be a better way. My first intuition would be to make my `(app)` layout blocking further execution until a Session Request has been resolved, but I have no clue how to achieve that. Do you think this would be doable or is there maybe another solution to my dilemma that comes to mind?

As a sidenote: Because of the nature of this problem, turning off SSR doesn't solve it either, unfortunately, since Solid would still go through all routes and start any requests client-side which ultimately leads to the same outcome.

I am sorry for bothering you with this. Again, I hope you or other users of this library would find some use in solving this case, since it's not really out-of-this-world.
I appreciate any help in advance 🙏 

**Edit:**
Just want to add one course of action that I had tried already and that was to intercept the API call in the API Provider and turn it into a resource that resolves only after the Authorization Header has been set.

The API Data is returned but I ran into trouble embedding a resource into a resource like `createRouteData`, e.g.
The change of the inner resource did not get propagated to the useRouteData() call itself. Maybe I misused the syntax but I tried a few different ways and none of them worked :/ I also get a ton of hydration errors using this approach

**Comment by emdede** [comment]
This is latest code where I tried to intercept the API request (see edit from OP) but I don't intend on solving this specific code block, I just would like to find a general solution. Can be completely different from this. But I did feel like I should show some code to give a better understanding of the whole situation.

APIProvider
```tsx
export const APIProvider: ParentComponent = (props) => {
  const [authHeader, setAuthHeader] = createSignal('')
  const [initialized, setInitialized] = createSignal(false)

  const session = createSession() as Accessor<CustomSessionContextInner>

  createRenderEffect(() => {
    const token = session()?.data?.user?.accessToken
    if (token) {
      setAuthHeader(token)
      setInitialized(true)
    } else {
      setAuthHeader('')
      setInitialized(false)
    }
  })

  const client = createTRPCProxyClient<AppRouter>({
    links: [
      loggerLink(),
      httpBatchLink({
        url: `${config.appUrl}/api/trpc`,
        headers() {
          return { Authorization: authHeader() }
        },
      }),
    ],
  })

  const request = <T extends AnyFunction>(cb: T) =>
    createResource(initialized, async (ready) => {
      if (!ready) return undefined
      return await cb()
    })

  return (
    <APIContext.Provider value={{ request, client }}>
      {props.children}
    </APIContext.Provider>
  )
}
```

(app).tsx
```tsx
export const routeData = () => {
  const { client, request } = useAPI()

  createServerData$(async (_, { request }) => {
    const serverSession = await getSession(request, authOpts)
    if (!serverSession) throw redirect('/login')
  })

  const [customers] = request(() => client.customer.list.query())
  return customers
}

export default function ProtectedLayout() {
  const customers = useRouteData<typeof routeData>()

  return (
    <Show when={customers()} fallback={<LoadingSpinnerCard />}> // <- always showing fallback + getting hydration errors
       ...
     </Show>
  )
}
```

**Comment by OrJDev** [comment]
> Hi! First off, I'm glad to see that you went ahead and released a follow-up version, seeing that your changes to next-auth are a bit stalled. I appreciate your work on this!
> 
> 
> 
> I ran into an issue that has been blocking me for several hours already and I can't seem to overcome it. It is actually more of a general Solid problem but because of the tight coupling of the problem with Auth I was hoping it'd be okay if I raise this here.
> 
> 
> 
> I have following setup (simplified):
> 
> ```tsx
> 
> <SessionProvider>
> 
>   <APIProvider>
> 
>     <Routes />
> 
>   </API>
> 
> </Session>
> 
> ```
> 
> 
> 
> Routes are
> 
> ```
> 
> login.tsx
> 
> (app).tsx <--- auth-protected entry point layout
> 
> app/
> 
>   all my routes...
> 
> ```
> 
> 
> 
> I have implemented Credentialsprovider (which took much longer than I had liked) and it is working fine!
> 
> 
> 
> However due to some implementation detail I am facing a big obstacle.
> 
> The `APIProvider` listens to session changes and sets an `accessToken` (that is included in the session data) as an `Authorization` header.
> 
> CSR (login first and get redirected into protected space) is working because the session - including the token - is available after signin.
> 
> However, if there is an SSR request to a nested route that uses the API. I can no longer use my setup because the session has not yet been initialized and the Authorization header is not set.
> 
> 
> 
> Now, I could probably micromanage this and go into every single sub-route to tell the API request to wait for the session to be retrieved first but it's tedious and brittle. I'm thinking there must be a better way. My first intuition would be to make my `(app)` layout blocking further execution until a Session Request has been resolved, but I have no clue how to achieve that. Do you think this would be doable or is there maybe another solution to my dilemma that comes to mind?
> 
> 
> 
> As a sidenote: Because of the nature of this problem, turning off SSR doesn't solve it either, unfortunately, since Solid would still go through all routes and start any requests client-side which ultimately leads to the same outcome.
> 
> 
> 
> I am sorry for bothering you with this. Again, I hope you or other users of this library would find some use in solving this case, since it's not really out-of-this-world.
> 
> I appreciate any help in advance 🙏 
> 
> 
> 
> **Edit:**
> 
> Just want to add one course of action that I had tried already and that was to intercept the API call in the API Provider and turn it into a resource that resolves only after the Authorization Header has been set.
> 
> 
> 
> The API Data is returned but I ran into trouble embedding a resource into a resource like `createRouteData`, e.g.
> 
> The change of the inner resource did not get propagated to the useRouteData() call itself. Maybe I misused the syntax but I tried a few different ways and none of them worked :/ I also get a ton of hydration errors using this approach

The thing about createSession is very weird: https://github.com/solidjs/solid-start/issues/830

The code is clean and simple and returns the correct data but for some reason solid's hydration only hydrates part of app and it doesn't like it at all, I recommended fetching the session from the server (using createServerData$ for now) until this issue has been fixed, this may take some time because no one has bothered to look at the issue atm

**Comment by emdede** [comment]
For reference, I finally managed to get it to work, but I did have to go the dreaded route of micromanaging my routeDatas everywhere. But I think this is just a Solid-inherent problem (as of now at least).

In (app).tsx, a bit hacky but I couldn't get it to work otherwise
```ts
export const routeData = () => {
  const session = createServerData$(async (_, { request }) => {
    const session = (await getSession(request, authOpts)) as CustomSession
    if (!session) throw redirect('/login')
    return session
  })

  const { client, setAuthToken, authToken } = useAPI()
  if (session() && !authToken()) {
    setAuthToken(session()!.user.accessToken)
  }
  
  const memo = createMemo(() => {
    if (!authToken()) return () => undefined
    return createResource(() => client.customer.list.query())[0]
  })

  // If the resource returns undefined, suspense will never resolve
  return memo()
}
```

Any other routeData
```ts
export function routeData(args: RouteDataArgs<RootRouteData>) {
  if (!args.data()) return () => undefined

  const { client } = useAPI()
  return someKindOfResource(client)
}
```
