### ISSUE TITLE
Peer version ranges are incorrect

### ISSUE THREAD

**Issue by thislooksfun** [OrJDev/solid-auth#27]
Currently trying to install `@solid-auth/core@0.0.6` + `@solid-auth/socials@0.0.6` fails with an invalid peer dependency error. This is because the versions currently match `0.0.x` which causes the caret range operator to treat _all_ updates as breaking. For example, the version range `^0.0.1` is parsed as `>= 0.0.1, < 0.0.2`. You should either bump the 'minor' version to be `0.1.x` or change the peer ranges to use `~` instead (like `~0.0.1`). The [npm server calculator](https://semver.npmjs.com) is a really handy resource for debugging version ranges.

**Comment by OrJDev** [comment]
Oh sorry about that I didn't notice, use --force for now and today i will change the operator to ~

**Comment by OrJDev** [comment]
fixed - https://github.com/OrJDev/solid-auth/commit/653d9d4b0399d8c1a6891e3c13602465be88aaec
